INSERT INTO SUKELTAJA (ETUNIMI, SUKUNIMI, LUOKITUS, PUHELINNUMERO, EMAIL)
    VALUES ('Erkki', 'Esimerkki', 'NAUI MSD', '555-123456', 'erkki@internez.net');

INSERT INTO SUKELTAJA (ETUNIMI, SUKUNIMI, PUHELINNUMERO, EMAIL)
    VALUES ('Sanna', 'Sukeltaja', '123-227774', 'sannas@dive.org');
    
INSERT INTO KOHDE (NIMI, SIJAINTI, KOHDETYYPPI, MINIMISYVYYS, KUVAUS)
    VALUES('Coolaroo', 'Helsinki', 'wreck', 15, 'Kyljellään makaava teräslaivan hylky');
    
INSERT INTO KOHDE (NIMI, SIJAINTI, KOHDETYYPPI, MINIMISYVYYS, KUVAUS)
    VALUES('Paakkilan avolouhos', 'Tuusniemi', 'mine', 10, 'Vedellä täyttynyt kirkasvetinen vanha asbestiluohos');

INSERT INTO SUKELLUS (SUKELTAJA_ID, KOHDE_ID, NUMERO, PVM, SUKELLUSAIKA, POHJA_AIKA, SUURIN_SYVYYS, NAKYVYYS, ILMAN_LAMPOTILA, VEDEN_LAMPOTILA, PUKUTYYPPI, LAITTEEN_KOKO, ALKUPAINE, LOPPUPAINE, KAASUTYYPPI, KAASUN_HAPPIPROSENTTI)
    VALUES ((SELECT SUKELTAJA_ID FROM SUKELTAJA WHERE ETUNIMI = 'Erkki'), (SELECT KOHDE_ID FROM KOHDE WHERE NIMI = 'Coolaroo'), 50, '2011-06-08', 40, 30, 22, 6, 18, 10, 'dry', 14, 210, 90, 'nitrox', 32);

INSERT INTO SUKELLUS (SUKELTAJA_ID, KOHDE_ID, NUMERO, PVM, SUKELLUSAIKA, POHJA_AIKA, SUURIN_SYVYYS, NAKYVYYS, ILMAN_LAMPOTILA, VEDEN_LAMPOTILA, PUKUTYYPPI, LAITTEEN_KOKO, ALKUPAINE, LOPPUPAINE, KAASUTYYPPI)
    VALUES ((SELECT SUKELTAJA_ID FROM SUKELTAJA WHERE ETUNIMI = 'Sanna'), (SELECT KOHDE_ID FROM KOHDE WHERE NIMI = 'Paakkilan avolouhos'), 23, '2012-09-09', 45, 40, 16, 8, 16, 7, 'wet', 12, 280, 130, 'air');
    

