INSERT INTO DIVER (FIRSTNAME, LASTNAME, CLASSIFICATION, PHONENUMBER, EMAIL, PSWD)
    VALUES ('Erkki', 'Esimerkki', 'NAUI MSD', '555-123456', 'erkki@internez.net', 'erkki');

INSERT INTO DIVER (FIRSTNAME, LASTNAME, PHONENUMBER, EMAIL, PSWD)
    VALUES ('Sanna', 'Sukeltaja', '123-227774', 'sannas@dive.org', 'sanna');

INSERT INTO SPOT (NAME, LOCATION, SPOTTYPE, MINDEPTH, DESCRIPTION)
    VALUES('Coolaroo', 'Helsinki', 'wreck', 15, 'Kyljellään makaava teräslaivan hylky');

INSERT INTO SPOT (NAME, LOCATION, SPOTTYPE, MINDEPTH, DESCRIPTION)
    VALUES('Paakkilan avolouhos', 'Tuusniemi', 'mine', 10, 'Vedellä täyttynyt kirkasvetinen vanha asbestiluohos');

INSERT INTO DIVE (DIVER_ID, SPOT_ID, NUMBER, DIVEDATE, DIVETIME, BOTTOMTIME, MAXDEPTH, VISIBILITY, AIRTEMP, WATERTEMP, SUITTYPE, TANKSIZE, STARTPRESSURE, ENDPRESSURE, GASTYPE, OXYGEN_PERCENTAGE)
    VALUES ((SELECT DIVER_ID FROM DIVER WHERE FIRSTNAME = 'Erkki'), (SELECT SPOT_ID FROM SPOT WHERE NAME = 'Coolaroo'), 50, '2011-06-08', 40, 30, 22, 6, 18, 10, 'dry', 14, 210, 90, 'nitrox', 32);

INSERT INTO DIVE (DIVER_ID, SPOT_ID, NUMBER, DIVEDATE, DIVETIME, BOTTOMTIME, MAXDEPTH, VISIBILITY, AIRTEMP, WATERTEMP, SUITTYPE, TANKSIZE, STARTPRESSURE, ENDPRESSURE, GASTYPE)
    VALUES ((SELECT DIVER_ID FROM DIVER WHERE FIRSTNAME = 'Sanna'), (SELECT SPOT_ID FROM SPOT WHERE NAME = 'Paakkilan avolouhos'), 23, '2012-09-09', 45, 40, 16, 8, 16, 7, 'wet', 12, 280, 130, 'air');
