DROP TYPE IF EXISTS PLACE;
DROP TYPE IF EXISTS GAS;
DROP TYPE IF EXISTS SUIT;

CREATE TYPE SUIT AS ENUM ('DRY', 'WET');
CREATE TYPE GAS AS ENUM ('NITROX', 'AIR');
CREATE TYPE PLACE AS ENUM ('WRECK', 'BIO', 'MINE');

CREATE TABLE DIVER
(
DIVER_ID SERIAL PRIMARY KEY,
FIRSTNAME VARCHAR(64) NOT NULL,
LASTNAME VARCHAR(64) NOT NULL,
CLASSIFICATION VARCHAR(64),
PHONENUMBER VARCHAR(64),
EMAIL VARCHAR NOT NULL(64)
);

CREATE TABLE SPOT
(
SPOT_ID SERIAL PRIMARY KEY,
NAME VARCHAR(128) NOT NULL,
LOCATION VARCHAR(128),
SPOTTYPE PLACE NOT NULL,
MINDEPTH INT,
DESCRIPTION VARCHAR(2048)
);

CREATE TABLE DIVE
(
DIVE_ID SERIAL PRIMARY KEY,
DIVER_ID INT NOT NULL REFERENCES DIVER(DIVER_ID),
SPOT_ID INT NOT NULL REFERENCES SPOT(SPOT_ID),
NUMBER INT NOT NULL,
DIVEDATE DATE NOT NULL,
DIVETIME TIME NOT NULL,
BOTTOMTIME INT NOT NULL,
MAXDEPTH REAL NOT NULL,
VISIBILITY INT NOT NULL,
AIRTEMP INT NOT NULL,
WATERTEMP INT NOT NULL,
SUITTYPE SUIT NOT NULL,
TANKSIZE INT NOT NULL,
STARTPRESSURE INT NOT NULL,
ENDPRESSURE INT NOT NULL,
GASTYPE KAASU NOT NULL,
OXYGEN_PERCENTAGE INT NOT NULL DEFAULT 21,
DESCRIPTION VARCHAR(2048)
);




