USE divelog

CREATE TABLE DIVER
(
DIVER_ID INT NOT NULL AUTO_INCREMENT,
FIRSTNAME VARCHAR(128) NOT NULL,
LASTNAME VARCHAR(128) NOT NULL,
CLASSIFICATION VARCHAR(128),
PHONENUMBER VARCHAR(128),
EMAIL VARCHAR(128) NOT NULL,
PSWD VARVHAR(128) NOT NULL
);

CREATE TABLE SPOT
(
SPOT_ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(256) NOT NULL,
LOCATION VARCHAR(256),
SPOTTYPE ENUM('wreck', 'bio', 'mine') NOT NULL,
MINDEPTH INT,
DESCRIPTION TEXT(4096)
);

CREATE TABLE DIVE
(
DIVE_ID INT NOT NULL AUTO_INCREMENT,
DIVER_ID INT NOT NULL,
SPOT_ID INT NOT NULL,
DIVENUMBER INT NOT NULL,
DIVEDATE DATE NOT NULL,
DIVETIME INT NOT NULL,
BOTTOMTIME INT NOT NULL,
MAXDEPTH DECIMAL(4,1) NOT NULL,
VISIBILITY INT NOT NULL,
AIRTEMP INT NOT NULL,
WATERTEMP INT NOT NULL,
SUITTYPE ENUM('wet', 'dry') NOT NULL,
TANKSIZE INT NOT NULL,
STARTPRESSURE INT NOT NULL,
ENDPRESSURE INT NOT NULL,
GASTYPE ENUM('nitrox', 'air') NOT NULL,
OXYGEN_PERCENTAGE INT NOT NULL DEFAULT 21,
DESCRIPTION TEXT(4096) NOT NULL
);

ALTER TABLE DIVE
ADD CONSTRAINT DIVE_DIVER_FK
FOREIGN KEY (DIVER_ID)
REFERENCES DIVER(DIVER_ID)
FOREIGN KEY (SPOT_ID)
REFERENCES SPOT (SPOT_ID);


